Repository PiotrMaciejKowalski/ts-r, pull requests merged in 2019-05, with the labels that each got.

#64 zad 3 Mruk -Play
  cw3/GPW_PLAY.csv
  cw3/GPW_PLAYYY.Rmd
Labels: Zad3

#87 Cw 3 - Kielbik - GPW-KRU
  cw3/Kielbik-kru_d.csv
  cw3/Kielbik_GPW-KRU.Rmd
Labels: Zad3

#88 rozwiazanie zadania 3
  cw3/Ladka-GPW-CCC.xlsx
  cw3/Ladka-cw3-GPW.rmd
Labels: Zad3

#89 Rozwiązanie zadania 4
  cw4/akaminska-data.csv
  cw4/kaminska-zadanie4.Rmd
Labels: Zad4

#90 Cw4 kolanowska patrycja
  cw4/PKolanowska-FEX-USD-CAD.Rmd
  cw4/pKolanowska-USDCAD.csv
Labels: Zad4

#92 A szczepaniak zad 4
  cw4/aszczepaniak-aat_d.Rmd
  cw4/aszczepaniak-data.csv
Labels: Zad4

#99 Cw5 szymanska
  cw5/JSzymanska_VividGames.Rmd
  cw5/JSzymanska_dane.csv
Labels: Zad5

#94 Rozwiązanie zadania 3
  cw3/kaminska-USD-CHF1.csv
  cw3/kaminska-USD-CHF3.Rmd
Labels: Zad3

#93 Wysyłam rozwiąznie zadania 3
  cw3/FEX-AUD-NZD.Rmd
  cw3/mwozna-dane.csv
Labels: Zad3

#98 Cw4 czarkowska gpw awm
  cw3/awm_czarkowska.Rmd
  cw3/dane_awm.xlsx
  cw4/dane awm.txt
  cw4/mczarkowska-GPW-AWM.Rmd
Labels: Zad4

#101 Zadanie 3
  cw3/FEX-USD-CAD.Rmd
  cw3/pKolanowska-USDCAD.csv
Labels: Zad3

#105 Szczepaniak_Anna_Zadanie_3
  cw3/aszczepaniak-data.csv
  cw3/szczepaniak-cw3.Rmd
Labels: Zad3

#107 Cw 5 Kielbik - GPW-KRU
  cw5/Kielbik-GPW-KRU.Rmd
  cw5/Kielbik-kru_d.csv
Labels: Zad5

#108 Cw5 mruk
  cw5/KMruk-GPW_Play.Rmd
  cw5/kMruk-GPW_PLAY.csv
Labels: Zad5

#112 Rozwiązanie zadania 5
  cw5/jkaminska-USD-CHF.Rmd
  cw5/jkaminska-dane.csv
Labels: Zad5

#96 dodano rozwiązanie zadania 4
  cw4/amalarski-agora-gpw.txt
  cw4/cw4-malarski-agora-gpw.Rmd
Labels: Zad4

#102 Dodano rozwiązanie zadania3
  cw3/amalarski-agora-gpw.txt
  cw3/cw3-malarski-agora-gpw.Rmd
Labels: Zad3

#100 rozwiazanie zad 4
  cw4/Choińska_Dane.csv
  cw4/DChoinska-zad4.Rmd
Labels: Zad4
