Repository PiotrMaciejKowalski/ts-r, pull requests merged in 2019-04, with the labels that each got.

#46 Predykcja EUR-TRY
  cw3/FEX-EUR-TRY.Rmd
  cw3/FEX-EUR-TRY.xlsx
Labels: Zad3

#59 Poprawione
  cw2/FEX-USD-CAD.Rmd
  cw2/USDCAD.csv
Labels: Zad2

#65 Notowania akcji spółki KRUK S.A. - poprawione
  cw2/Kielbik-GPW-KRU.Rmd
  cw2/Kielbik-kru_d.csv
Labels: Zad2

#73 rozwiazanie cwiczenia 1
  cw1/zestaw20.R
Labels: Zad1

#67 FEX-WTI-USD
  cw2/Kapucinska_FEX_WTI_USD.Rmd
  cw2/Kapucinska_WTI_USD.csv
Labels: Zad2

#72 Rozwiązanie zadania 2
  cw1/zestaw17.R
  cw2/kaminska-USD-CHF.Rmd
  cw2/kaminska-USD-CHF1.csv
Labels: Zad2

#77 Cw2 anna szczepaniak
  cw2/aat_d.csv
  cw2/aat_d_Szczepaniak.Rmd
Labels: Zad2

#52 Zadanie 3 v1
  cw3/GPW-VividGamesSA-dane.csv
  cw3/GPW_VividGamesSA.Rmd
Labels: Zad3

#66 Cw3 jadczak
  cw3/EURGBP.csv
  cw3/FEX-EUR-GBP.Rmd
Labels: Zad3

#54 Filtrowanie potokowe dla cen akcji ATP
  cw4/stobiecka-GPW-ATP.Rmd
  cw4/stobiecka-data.csv
Labels: Zad4

#55 Cw4 kowarik
  cw4/AKowarik-GPW-Amica.Rmd
  cw4/Akowarik-Amica-GPW.xlsx
Labels: Zad4

#61 Cw4 sobor gbp jpy
  cw4/ssobor-GBP-JPY.Rmd
  cw4/ssobor-data.csv
Labels: Zad4

#63 Cw4 jadczak eur gbp
  cw4/ajadczak-FEX-EUR-GBP.Rmd
  cw4/ajadczak-data.csv
Labels: Zad4

#60 Dodanie pierwszej wersji zadania 4
  cw4/jbujnowicz-GPW-mBank.Rmd
  cw4/jbujnowicz-data.csv
Labels: Zad4

#76 Cw4 wozna
  cw4/MWozna-FEX-AUD-NZD.Rmd
  cw4/mwozna-dane.csv
Labels: Zad4

#68 Modele ARIMA dla cen akcji ATP
  cw5/stobiecka-GPW-ATP-ARIMA.Rmd
  cw5/stobiecka-dane.csv
Labels: Zad5

#69 Rozwiązanie zadania 5 - prognozy ARIMA
  cw5/ssobor-FEX-GBP-JPY.Rmd
  cw5/ssobor-data.csv
Labels: Zad5

#70 Ćw 5 ARIMA dla 4FM
  cw5/aksiezak-GPW-4FM.Rmd
  cw5/aksiezak-data.csv
Labels: Zad5

#75 Pierwsza wersja prognoz z wykorzystaniem modeli ARIMA
  cw5/jbujnowicz-GPW-mBank.Rmd
  cw5/jbujnowicz-data.csv
Labels: Zad5

#78 Rozwiazanie zadania 5
  cw5/cw5-soja-octavasa.Rmd
  cw5/soja-data.csv
Labels: Zad5

#53 Rozwiazanie cwiczenia 3
  cw3/08n_d.csv
  cw3/cw3-soja-octavasa.Rmd
  cw3/soja-data.csv
Labels: Zad3

#71 zadanie_4_Szymanska
  cw4/GPW-VividGamesSA-dane.csv
  cw4/JSzymanska_GPW_VividGamesSA.Rmd
  cw4/jszymanska_dane.csv
Labels: Zad4

#74 zad 4 - Mruk Play
  cw4/kMruk-GPW_PLAY.Rmd
  cw4/kMruk-GPW_PLAY.csv
Labels: Zad4

#84 Cw4 kapucinska wti usd
  cw3/Kapucinska_WTI_USD.csv
  cw3/WTI_USD-Kapucinska.Rmd
  cw4/Kapucinska_WTI_USD.Rmd
  cw4/Kapucinska_WTI_USD.csv
Labels: Zad4

#86 Cw 4 - Kielbik - GPW-KRU
  cw4/Kielbik-GPW-KRU.Rmd
  cw4/Kielbik-kru_d.csv
Labels: Zad4

#79 Rozwiązanie zadania 5 - prognozy ARIMA dla FEX-EUR-TRY
  cw5/astanczyk-FEX-EUR-TRY.Rmd
  cw5/astanczyk-FEX-EUR-TRY.xlsx
Labels: Zad5

#80 Rozwiązanie zadania 5
  cw5/ajadczak-FEX-EUR-GBP.Rmd
  cw5/ajadczak-data.csv
Labels: Zad5

#83 Rozwiązanie zadnia 5
  cw5/mwozna-FEX-AUD-NZD.Rmd
  cw5/mwozna-dane.csv
Labels: Zad5

#85 zadanie 5
  cw5/AKowarik-cw5.Rmd
  cw5/Akowarik-Amica-GPW.xlsx
Labels: Zad5

#81 rozwiązanie zadania 2
  cw2/Choinska-cw2.rmd
  cw2/Choińska_Dane.csv
Labels: Zad2
