Repository PiotrMaciejKowalski/ts-r, pull requests merged in 2019-06, with the labels that each got.

#111 Cw3 kapucinska wti usd v3
  cw3/WTI_USD_Kapucinska.Rmd
Labels: Zad3

#113 Rozwiązanie zadania 5
  cw5/Kapucinska_WTI_USD.Rmd
  cw5/Kapucinska_WTI_USD.csv
Labels: Zad5

#119 rozwiązanie zad3
  cw3/Choinska-zad3.Rmd
  cw3/Choińska_Dane.csv
Labels: Zad3

#114 rozwiazanie zadania 5
  cw4/Ladka-GPW-CCC.xlsx
  cw5/Ladka-GPW-CCC.xlsx
  cw5/Ladka-cw5.rmd
Labels: Zad5

#116 Cw5 czarkowska
  cw5/mczarkowska-gpw-awm.Rmd
  cw5/mczarkowska-gpw-awm.xlsx
Labels: Zad5

#120 rozwiązanie zadania 5
  cw5/amalarski-agora-gpw.Rmd
  cw5/amalarski-agora-gpw.txt
Labels: Zad5

#121 Zadanie 5
  cw5/aszczepaniak-data.csv
  cw5/aszczepaniak_atp_d.Rmd
Labels: Zad5

#118 rozwiazanie zad 5
  cw5/Choinska-cw5.Rmd
  cw5/Choinska_Dane.csv
Labels: Zad5

#124 pierwsza wersja ćwiczenia
  cw1/zestaw8.R
Labels: Zad1

#125 Pierwsza wersja ćwiczenia 2
  cw2/cw2-dudaczyk-GPW-WOJAS.Rmd
  cw2/dudaczyk-GPW-WOJAS.csv
Labels: Zad2

#126 Cw3 dudaczyk
  cw3/cw3-dudaczyk-GPW-WOJAS.Rmd
  cw3/dudaczyk-GPW-WOJAS.csv
Labels: Zad3

#127 Pierwsza wersja ćwiczenia 4
  cw4/dudaczyk-GPW-WOJAS.csv
  cw4/dudaczyk-cw4-GPW-WOJAS.Rmd
Labels: Zad4

#130 Pierwsza wersja ćwiczenia 5
  cw5/dudaczyk-GPW-WOJAS.csv
  cw5/dudaczyk-cw5-GPW-WOJAS.Rmd
Labels: Zad5
