Repository PiotrMaciejKowalski/ts-r, pull requests merged in 2019-03, with the labels that each got.

#29 zadanie2, Michał Szumicki, ZAR/JPY
  cw2/Dane.csv
  cw2/Dane.xlsx
  cw2/FEX-ZAR-JPY.Rmd
Labels: Zad2

#39 Zadanie2
  cw2/08n_d.csv
  cw2/cw2-soja-wersja2.Rmd
Labels: Zad2

#38 Predykcja dla kursów GBP-JPY
  cw3/FEX-GBP-JPY.Rmd
  cw3/GBP-JPYg.csv
Labels: Zad3

#40 Cw2 jadczak fex eur gbp
  cw2/EURGBP.csv
  cw2/FEX_EUR_GBP.Rmd
Labels: Zad2

#41 Cw2 czarkowska gpw amw
  cw2/GPW-AWM.Rmd
  cw2/dane_awm.csv
  cw2/dane_awm.xlsx
Labels: Zad2

#45 Zad2 Mruk Play
  cw2/GPW_PLAY.csv
  cw2/GPW_PLAYYY.Rmd
Labels: Zad2

#47 Prognozowanie cen akcji ATP z użyciem modeli liniowych
  cw3/GPW_ATP_Prognoza.Rmd
  cw3/atp_d.csv
Labels: Zad3

#49 Predykcja 4FM
  cw3/GPW-4FUNMEDIA-csv2.csv
  cw3/GPW_4FUNMEDIA.Rmd
Labels: Zad3

#48 Cw3 kowarik gpw amica
  cw3/Amica_GPW_Kowarik.xlsx
  cw3/GPW-kowarik.Rmd
Labels: Zad3

#51 Rozwiązanie zadania 4
  cw4/aksiezak-GPW-4FM.Rmd
  cw4/aksiezak-data.csv
Labels: Zad4
